name: schedule

on:
  schedule:
    # Execute every 3 hours
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Ho_Chi_Minh

    steps:
      # Clone repo
      - name: Clone repo
        uses: actions/checkout@v2

      # Setup python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # Config git
      - name: Config git
        run: |
          git config --local user.email "minhhoangho99@gmail.com"
          git config --local user.name "Hoang Ho Minh"
          git remote set-url origin "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}"
          git pull --rebase
      # Run python
      - name: Run python
        run: python main.py

      # Push to repo
      - name: Update repo
        run: |
          git add .
          git commit -m "Auto update trending"
          git push -u origin main
